### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by hanbings** [Cup0fCode/5x5Crafting#1]
Hello, I found some problems in your project, located at fiveByFiveCrafting.recipes.RecipeManager#50 
to fiveByFiveCrafting.recipes.RecipeManager#58

  If I use Bukkit#clearRecipe before this method, using Bukkit#recipeIterator or Bukkit#getRecipeFor will cause NoSuchElementException when the recipe is cleared.

  My solution is to judge whether the result of Bukkit#recipeIterator is empty before using hasNext and next, or add a recipe that cannot be synthesized
For example, a stone made of nine Bedrocks

**Comment by bluefoxy009** [comment]
You should make a pull request my guy

**Comment by hanbings** [comment]
Oh, seems like I forgot about this at the time, but it's been so long that I'm not sure if I remember any specific details about this plugin.

**Comment by hanbings** [comment]
I tried to re-fork the project to make changes, but because of lack of dependencies, I couldn't complete the compilation and testing, so I decided not to do a normal PR, but I still submitted a Close PR that fixes the problem. https://github.com/Cup0fCode/5x5Crafting/pull/2 

One more thing, this project has not been updated for a long time, if you encounter problems, maybe you can ask the author of this plugin.
